### ISSUE TITLE
Discussion: single and first behavior

### ISSUE THREAD

**Issue by alercunha** [zbra-solutions/android-linq#3]
Should single and first throw an exception or return null by default?

When writing code what is preferred?

```
int? x = list.single(x -> x == 2);
if (x == null)
    // throw exception
```

Or

```
int x = list.single(x == 2); // will throw an exception because there's no 
```

The alternative would be:

```
int? x = list.singleOrDefault(x -> x == 2);
```

Why was the behavior of single and first chosen to be "return default(T) in case it doesn't find the item"?

**Comment by sergiotaborda** [comment]
Mainly because you don't have a Nullable<T> where T is anything in C# So IEnumerable cannot return Nullable of String> or Nullable of Client or wahtever... tha's why we need Optional/Maybe type or in linq's case singleorDefault 

In java you can create your own Optional type (like exists in java 8) or create a signature like

```
int x = list.singleOrDefault(x -> x == 2 , 8); // 8 is the default value
```

On the other hand , throwing exception is a good thing and the only purpose of single. Single forces that only one element is in the stream and this is ofen coupled with business logic and rules. Otherwise using First would suffice. However, in the java world collections may contain null as a valid element, so there is a diference between returning null because the element in the collection is null, or because the collection is empty. 

so this expressions are not equivalent

```
stream.any() ==  ( stream.first() == null)
```

example a not inicialized array of any object

```
String[] array = new String[7];

stream.any() == true // because length == 7
stream.first() == null // becasue that's the value in the first index

String[] array = new String[0];

stream.any() = false // because array is empty
stream.first()  throws exception // becasue that are no elements. returning null would be incorrect
```

A method stream.first() returning an Optional resolves both cases. This is the selected path for the java 8 stream, findfirst returns Optional. No method returns null , no method throws exception.

**Comment by alercunha** [comment]
So are you advocating single should throw an exception or returns an Optional?

Looks like both first and single methods implementations must be changed right?

**Comment by sergiotaborda** [comment]
According to .NET API single should throw an exception It exists because of that exception. In the case we do not want an exception remove single from the API and only use first. But fisrt should return Optiona l. 

Its a paradigm problem. Should android linq follow java rules becasue its to be used in the java envroirment , and so, should it be compatible with java 8 Stream , or it should follow .NET API design and rules , and so , should it follow .NET design incompletion also ? 
The incompletion problem in .NET is not a problem because method extentions exist to address that, but a incomplete design in java is undicaped forever. :-)

**Comment by brunovinicius** [comment]
There's no firstOrDefault() nor singleOrDefault() because I don't like them. 
I have never made an assessment on the subject like you are doing. 

If the collection is empty, though, I think its fine for the method to return null. Does't really matter the reasons why the element was not found, if the collection is empty or there was no element matching the passed predicate is mostly not relevant, right? So why bother?

The thing that bothers me is the scenario where null is a valid member of the collection. We could throw an runtime exception in both if the collection is empty for the sake of completeness. But that would force a any() call to make sure is secure to call single()/first().

Is it a common scenario? Is it worth the trading for the sake of simplicity?

**Comment by alercunha** [comment]
You're missing the point. It's not about liking "OrDefault" or not. This way methods are not consistent and will cause confusion/bugs for clients.

`list.single()` has to throw an exception if no element is present because that's the purpose of calling it "single". It means "there is a single object in that list". If there is no object and you return null then you're not sure if the object being returned is null because that's the value you were looking for or if there were no values.

```
a = ["a", null, "b"];
b = a.single(s -> s == null);
```

If b has null now what?

The same logic applies for first.

**Comment by sergiotaborda** [comment]
Let's try this for size:

Current implementations are 

```
 @Override
public boolean any() {
    return first() != null;
}

@Override
public T first() {
    Iterator<T> iterator = iterable.iterator();
   if (iterator.hasNext()){
       return iterator.next();
   }
   return null;
}
```

1) Any should not depend on first. It's the other way around. Any is a "primitive" method (not derived from othes) and should be , simply

```
public boolean any() {
return this.iterator().hasNext();
}
```

2) First cannot assume null is a "third value" , meaning , it can be a real, present value. So "null" should not appear on the code of first

```
public T first() {
Iterator<T> iterator = iterable.iterator();
if (iterator.hasNext()){
   return iterator.next(); // may return null, if it is really present in the collection
}
throw new NoElementFoundException()
```

This follows .NET contract.

The principle being this thing we first and firtOrDefault, is that: "Null is Evil". 
So .NET avoids it. But at te cost of making the same mistake we are trying to avoid ( using a valid value as meaning "nothing"). They choose to return default(T) that is null for all non struct T... bad choise. Now, when firstOrDefault returns null is it because it's there in the collection, of because the collection is empty ? no way of knowing... it's even worse with numbers has 0 e a valid number most of the time.
Nevertheless default(T) does not exit in java (you cannot crate generic class with pimitives) so null is the de facto default. This is no good beacause we what to avoid it. 

3) firstOrDefault does not translate with the same signature com .net to java. In .net it means 

```
public T firstOrDefault() {
Iterator<T> iterator = iterable.iterator();
if (iterator.hasNext()){
   return iterator.next();
}
return default(T);
```

In java means 

```
public T firstOrOtherValue( T otherValue) {
Iterator<T> iterator = iterable.iterator();
if (iterator.hasNext()){
   return iterator.next();
}
return otherValue;
```

You can pass null has the otherValue, but that is the programmer's choice, not the API. Also you can pass any other value you like

**Comment by brunovinicius** [comment]
@alercunha The method single() already throws an exception if theres duplicates.
@sergiotaborda 
1) Completely agreed. Its a bug.
2) Its true that this might be an scenario, but I dont think its worth the hassle. What's the point of getting a null element from a collection? You might get a element which has some property == null, which is possible. In my humble opinion, throwing an exception does not help much. If get an null element from the collection what are you suposed to do with it, anyway?
3) I think we could do something like this. Its an adittional method which will be called by the existing with null as default value.

**Comment by alercunha** [comment]
My example was wrong. I meant to write this:

```
v = "c"
a = ["a", null, "b"];
b = a.single(s -> s == v);
if (b == null)
    // then what? is it because there is no single or because it matched something?
```

Now you have to compare the value of b with the value of v but if v came from a function argument then things get difficult.

Overall I agree with Sergio. There are some changes needed to keep the whole thing more consistent and eliminating the null value and putting an exception is part of the solution. Adding another method singleOrDefault(T val) will also help.

For now there are a few important bugs to fix:

1 - any() behavior cannot be based on the value of first
2 - single() must throw an exception if no value matches and stop returning null
3 - first() cannot return null if there's no elements if must throw an exception as well

**Comment by sergiotaborda** [comment]
What's the point of getting a null element from a collection ? Well, there must be some point, the current api already does that. Returning what's inside the collection is correct. The API should return whatever is in the collection. 
The point is that the current implementation _also_ returns null when the collection is empty. 
This is the cause of ambiguity. Neither java stream nor .net ienumerable are ambiguous like this. 

You may understand this is not a cause of confusion for the end programmer, but it is and the current code already makes it. It uses first == null to test if the collection is empty in the any() method. This is was the point i was trying to make previously, sorry if was not clear.  Because is not true that first == null is equivalent to any() == false first should never return null when the collection is empty. 
IF first returns null , the programmer may be persuaded to use it instead of any and arriving to false conclusions. Imagine the programmer must decide to execute some code if the collection is not empty, 

```
if (stream.any() ){ // what he means
   // do something 
}
```

but the programmer writes

```
if (stream.first() != null ){ // what he writes
   // do something 
}
```

for a collectiion [null, 2, 4]  the code wil not be executed even when the stream is not empty failing the busines logic. You could argue the problem is that no nulls shoul be present in the collection to start with, ok, but that is not a requirement of the original collection, why make it a requirement of a complementary , helper , api ? 

If the programmer supects nulls may be present he will write

```
if (stream.where ( a -> a != null).any()){

}
```

Why do you insist of making first() return null when the collection is empty ? try to execute Queue.getFirst our LinkendList.getFirst  on empty collections , what is expected ? An exception, why should be any different in this API ? 

I agreed the design should follow the original ienumerable rules.

**Comment by fabiofalavinha** [comment]
I think the API must raise an exception on "first" and "single" stream collection methods for empty collections.

Use "..OrDefault" it's a mistake because default seems to retrieve a default typed value in .NET.
In java, you must use Optional, so like, you must use "...OrOptional" and pass the optinal value.

**Comment by brunovinicius** [comment]
I think you are comparing too much. This is not IEnumerable clone not Stream nor Java Collections.
We can do what the fuck we want. its OUR implementation with OUR compromises and OUR contracts. I say returning null for empty collection is fair, if our DOCs state so clearly I think its fine.

@sergiotaborda 
- 1st example is right and should work no matter what. 
- 2nd example is wrong. The programmer gets to deal with his error. No patronizing. Also if he knows no null will rest inside his collection it works just fine.
- 3rd example is also right. Is probably what you do when there may be null on your collection. I used it on Kraken and it works fine also...

The point is. Do we need or want to comply with IEnumerable or Collections or Steam? Why? Is it realy that bad for the programmer to check for null return?

**Comment by alercunha** [comment]
If this is a library that will be used in a single project then fine, just decide whatever you want. If not then you need to comply with what people wants. People here want changes! 

Fora PT! Fora Lula!!!

**Comment by fabiofalavinha** [comment]
Yep... let's make a "Panelaço" if Bruno doesn change the API!!!! :P

**Comment by brunovinicius** [comment]
I ask for a little of patience and comprehension coz this situation is transitory...

**Comment by brunovinicius** [comment]
I deleted bullshit comments for good measure.

I was talking to @fabiofalavinha and I think I might get a solutions which is good  for us all.
I think the problem is that I'm trying to provide only the singleOrDefault() implemenentation and you are telling me to implement the single()/first() implementation. I think both of us have a point and besides that LINQ provides both so I guess that is the real problem, right?

Is its ok if I rename the current implementation to singleOrNull() and get the single() raising the damn exceptions? Can we all agree on this path!?

**Comment by alercunha** [comment]
Yup, now you get the point!
single() shouldn't have been called single() in the first place.

**Comment by alercunha** [comment]
No reason to get carried away...
If you're opening your API to the public you must be ready to hear criticism.

**Comment by brunovinicius** [comment]
And Im suposed to take the opinions as truth or else my API gets deemed "useless" because of a methods name, right? _xei dos milindres_ 

My implementation wasn't the problem, the problem was the either/or position we all got into... and we only got here because I didn't blindly accept your suggestions. No hard feelings, I actually find these  conversations very fun =) 

But, its no over yet, @sergiotaborda has to chime in.

**Comment by brunovinicius** [comment]
Openned issue #8 chosing this as dup
