### ISSUE TITLE
first() has trouble when first value is null

### ISSUE THREAD

**Issue by alercunha** [zbra-solutions/android-linq#7]
Considering this is a valid scenario:

```
x = [null, "a", "b"];
b = x.first();
```

Now you do not know if b having null is because there is no values in the collection or because the first value is actually null.

An exception must be thrown in this case.

**Comment by brunovinicius** [comment]
Consider 3 following scenarios:

1) I know there's elements in the collection and I know there's no null elements (draw)
    - Nothing changes both current and your suggested implementation work fine

2) I know there might be some or none elements in my collection (draw)
    - My: I call first() check null and move on
    - Yours: I MUST call any() else my program breaks

3) I know there might be one or not and that this element might be null
    - My: if I care, I call any() to check if there's elements then get first() to get the element and use both to know what is happening, If I don't which I'm assuming, is what happens most of the time, I call first() check only for null and move on.
    - Yours: You must stick to the  any() then first() or you get exceptions; Even if you do not care to do shit with the null element coming from the collection

Now considering 99% of the cases fall in the first two, why bother?
I say my way generates less bloat in most cases. Not having to check if the collection is empty() for calling first/single for me is a big plus. Thats why I did not go for the first() implementation and gone for the firstOrDefault() instead.  If my memory doesn't fail me, we mostly used singleOrDefault() in SeaCOLT anyway coz we were uttlerly annoyed by the damn exceptions. Have you no memory for god sake!?

Is my reasoning that broken? I don`t think there's nothing more straightforward than call a @Nullable method and get a NullPointerException in case it does' t return what you expect. Its so fair it hurts...

**Comment by franconassis** [comment]
Absolutely disagree... 
You're assuming the developer knows what is inside the collection. He doesn't.

What if I'm populating a collection from something coming outside of the system. In that case which is best, calling first() and then you test against what?

The API has to induce the developer to have less bugs in his code. The way you're implementing first() is very tricky and a bug will pass undetected.

The user might inadvertently be calling `return list.first()` for a method implementation and the caller of his method just does not know what is going on. The fact that you return the same value for two __very distinct scenarios__ is misleading.

Having a well defined behavior which is easily predictable is much preferred for public APIs.

**Comment by alercunha** [comment]
Absolutely disagree...
You're assuming the developer knows what is inside the collection. He
doesn't.

What if I'm populating a collection from something coming outside of the
system. In that case which is best, calling first() and then you test
against what?

The API has to induce the developer to have less bugs in his code. The way
you're implementing first() is very tricky and a bug will pass undetected.

The user might inadvertently be calling `return list.first()` for a method
implementation and the caller of his method just does not know what is
going on. The fact that you return the same value for two **very distinct
scenarios** is misleading.

Having a well defined behavior which is easily predictable is much
preferred for public APIs.

Plus once you change the behavior for single() to throw an exception then
first() should follow suit.

**Comment by brunovinicius** [comment]
Its impossible to write code to a collection you don't know. If you are in border code (web service call and shit) you get full defensive anyway. You would call any() and first() anyway. Catching the exception would never be a option anyway. Right?

Single has to follow first() and I won't change only one of them because that would be a real consistency problem, so when u I say first() I mean both.

**Comment by alercunha** [comment]
You have to change it or else the API is useless.

You deal with collections you have no control over all the time. User input
is an example.
When you use first() method you're basically trying to do a syntactic sugar
for:

```
if (list.length > 0)
    return list[0];
else
    throw
```

That's the whole point of having a method called first.
If you do not throw then you're forcing the user to do:

```
if (list.any())
    return list.first()
else
    throw
```

So there is no gain by having such method.

If you want to deal with the situation of having a "default" value returned
then you must have to distinct methods to accomplish that.
You could do:

```
x = list.first() // will throw if no values in the list
y = list.firstOrDefault(10) // will return 10 in case no values in the
```

list

That way it's up to the developer to chose. The way you are doing it is not
only a bad decision it's not consistent.

Another argument on this matter is that you ARE calling your API "LINQ" so
you do expect people to know what LINQ means and people will have certain
expectations. By doing the opposite of what link does you are just shooting
yourself in the foot.

Like I said, if all developers are requesting something and you're the only
one denying it, have you stop to think why? How come you are the only one
right?

**Comment by sergiotaborda** [comment]
I agree with Ale

When I create an API it's about 
1) Form. The API must intend something and provide the programmer to reach this goal with minimum efford
2) Contract. The API are only interfaces that dictate rules. This rules should be coerent inside de API and with the other API in the platform
3) Domain. The API must be usefull for power users in the domain, and simple to newbies in the domain. "Simple" means : it will not trick you to do wrong, and will warn you when you do wrong.

Implementation is _not_ the driver of the API , is a detail.

I'm a little lost here because we are ignoring this directives , so i'm not sure here we are getting at / comming from. Hence my comparations with other API that, in my opinion, do it right 
You can not do whatever you want if you what API to be successful. API Design is of upmost importance in the Java realm, and a poorly crafted API just won't cut it.

Having said that, my 2 cents for implementation: I intended to work in the code, but time constraint issue are stopping me, so to help us get to the point i'm donating the code from my own API 

This a standard code I use often to implement iterator correctly. Is more important in the filteriterator, but is also useful in other iterators that must consume the original iterator before returning something (like groupby)

```
public class FilteredIterator<T> implements Iterator<T> {

    private Predicate<T> predicate;
    private Iterator<T> original;
        private Element<T> next;

    /**
     * Constructor.
     * @param iterator
     * @param predicate
     */
    public FilteredIterator(Iterator<T> iterator, Predicate<T> predicate) {
        this.original = iterator;
        this.predicate = predicate;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean hasNext() {
        if (original.hasNext()){
            Element<T> item = fetchNext();
            if (item.isFound()){
                this.next = item;
                return true;
            } 
        } 
        return false;
    }

    private Element<T> fetchNext(){
        while(original.hasNext()){
            T n = original.next();
            if (predicate.apply(n).booleanValue()){
                return new Element<T>(n);
            }
        }
        return Element.noSuchElement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T next() {
        if (next == null){
            next = fetchNext();
        }
        T obj = next.object();
        next = null;
        return obj;
    }

}

class Element<T>{

    @SuppressWarnings("rawtypes")
    private static final Element NO_SUCH_ELEMENT = new NoSuchItem();


    @SuppressWarnings("unchecked")
    public static <U> Element<U> noSuchElement(){
        return NO_SUCH_ELEMENT;
    }


    private boolean isFound = true;
    private T object;

    /**
     * Constructor.
     * @param n
     */
    public Element(T n) {
        this.object = n;
        this.isFound = true;
    }

    public Element() {
        this.isFound = false;
    }

    public boolean isFound(){
        return isFound;
    }

    public T object(){
        return object;
    }

    public boolean isAfterLast(){
        return false;
    }

}
```

Null is not as a "third value" the Element class provides that idiom.

This code respects and obey the  [Iterator](http://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--) interface rules.

1) It returns null when null is present in the collection, and only then.
2) It throws NoSuchElementException when the collection is empty or the iterator as passed the last element in the collection respecting the contract that says "throws NoSuchElementException - if the iteration has no more elements" 
3)It allows for consecutive calls to .next() without calling hasNext() first ,like it.next().next() to get the second element.

The unit test should reflect this rules and test all iterators against them. Only then coverage will be 100% meaningful.

With this contract in place for all iterators in the API,  first() is simply

```
public T first(){
   return iterator().next();
}
```

The iterator will check itself for empty collections and pass-the-point calls.
If we do wish to offer some empty-free-checking , the firstOrNull and firstOrValue methods should be added to the API. 

```
public T firstOrNull(){
   return firstOrValue(null);
}

public T firstOrValue(T value){
   Iterator<T> it = iterator();
   return it.hasNext() ? value: it.next();
}
```

If we are _really_ serious about a _public_ stream API in 2015 we should consider the API form and domain and add Optional to the mix. Without this the API design will be outdated and the success limited ( we do not need to add this right away, but surly for the 1.0 version). Otherwise , what's the point of the API ? I, for one, i' m not comfortable providing a non state-of-the-art API, to the best of my knowledge. We need directives.

**Comment by brunovinicius** [comment]
Sergion can you repost this comment on the discussion issue (#3) I think we might have finally got into a conformatable middle ground and Im ready to GLADLY open issues to implement something akin to what you sugesting.=)

**Comment by brunovinicius** [comment]
And im closing this one with Won't fix if everyone agrees...
